Update

diff --git a/mpw-2/nucleo/scripts/yifive_boot/Makefile b/mpw-2/nucleo/scripts/yifive_boot/Makefile
--- a/mpw-2/nucleo/scripts/yifive_boot/Makefile
+++ b/mpw-2/nucleo/scripts/yifive_boot/Makefile
@@ -1,46 +1,16 @@
-
 export PATH=$PATH:/bin:/usr/local/bin/:../../venv/bin:/usr/bin/:.
 
-#DEV=/dev/cu.usbmodem3103
-#DEV=/dev/cu.usbmodem34203
+# --- automatically set ---
+#DEV=/dev/cu.usbmodem33203
+#DEV=/dev/ttyACM0
 DEV=/dev/ttyACM0
-#DEV=/dev/cu.usbmodem34103
-#FILES=main.py flash.mpy i2c.py gpio_config_builder.py config_io_o_h.hex config_io_o_l.hex
-FLASH=/media/dinesha/PYBFLASH/
-#FLASH=//Volumes/PYBFLASH/
-NUCLEO_CMD=
 
-
-boot:
-	rshell --port ${DEV} cp boot.py /flash
-
-# pip install rshell to use this target
-copy: compile
-	mpremote connect ${DEV} cp flash.mpy i2c.mpy gpio_config_builder.mpy nucleo_api.mpy gpio_config_def.mpy :
-	mpremote connect ${DEV} cp config_io_o.hex :
-	mpremote connect ${DEV} cp io_config.mpy :
-	mpremote connect ${DEV} cp main.py :
-	mpremote connect ${DEV} ls :
-
-#copy: compile
-#	rshell --port ${DEV} cp flash.mpy i2c.mpy gpio_config_builder.mpy nucleo_api.mpy gpio_config_def.mpy /flash
-#	rshell --port ${DEV} cp config_io_o.hex /flash
-#	rshell --port ${DEV} cp io_config.mpy /flash
-#	rshell --port ${DEV} cp main.py /flash
-#	rshell --port ${DEV} ls /flash
-
-# copies scripts to nucleo
-copy2: compile
-	cp flash.mpy i2c.mpy gpio_config_builder.mpy nucleo_api.mpy io_config.mpy ${FLASH}
-	cp config_io_o.hex ${FLASH}
-	cp main.py ${FLASH}
-	ls ${FLASH}
-
-copy3:
-	cp flash.py i2c.py gpio_config_builder.py nucleo_api.py io_config.py ${FLASH}
-	cp config_io_o.hex ${FLASH}
-	cp main.py ${FLASH}
-	ls ${FLASH}
+#FLASH=/media/efabless/PYBFLASH/
+#FLASH=/media/dinesha/PYBFLASH/
+FLASH=/media/PYBFLASH/
+DEV=$(shell mpremote connect list | grep STLink | cut -f 1 -d ' ')
+#COPY_CMD=rshell --port ${DEV} cp
+COPY_CMD=cp
 
 # cross compile python to micropython bin.
 
@@ -56,16 +26,49 @@ compile:
 	mpy-cross boot.py
 
 # runs script from the local filesystem
-reset:
+reset: check_device
 	#mpremote connect ${DEV} soft-reset
 	mpremote connect ${DEV} exec "import machine; machine.reset()"
 
-# alternate -- mpremote connect ${DEV} exec "import io_config; io_config.run()"
-run:
-	mpremote connect ${DEV} exec "import machine; machine.reset()"
+# runs script from the local filesystem
+version: check_device
+	@mpremote connect ${DEV} exec "import io_config; io_config.version()"
 
-get_config:
+# run io_config test to characterize a new part
+# alternate -- mpremote connect ${DEV} exec "import io_config; io_config.run()"
+# alternate -- mpremote connect ${DEV} exec "import machine; machine.reset()"
+run: check_device 
+	mpremote connect ${DEV} exec "import io_config; io_config.run()"
+
+# copy the definition file for a part after running io_config
+get_config: check_device
 	mpremote connect ${DEV} cp :gpio_config_def.py .
+
+# run a sanity check using the gpio_config_def.py file on the nucleo
+sanity_check: check_device
+ifndef FILE
+	$(error FILE is undefined, please export it before running make flash)
+else
+	$(COPY_CMD) ${FILE} ${FLASH}/gpio_config_def.py
+	sync
+	sleep 2
+	mpremote connect ${DEV} exec "import io_config; io_config.run_sanity_check($(VOLTAGE))"
+endif
+
+# power up the caravel hat while mounted to Nucleo
+poweron: check_device
+	mpremote connect ${DEV} exec "import io_config; io_config.run_poweron()"
+
+# flash firmware on caravel hat while mounted to Nucleo
+flash: check_volume check_device
+ifndef FILE
+	$(error FILE is undefined, please export it before running make flash)
+else
+	$(COPY_CMD) ${FILE} ${FLASH}/firmware.hex
+	sync
+	sleep 2
+	mpremote connect ${DEV} exec "import io_config; io_config.run_flash_caravel()"
+endif
 
 # enter repl on nucleo
 repl:
@@ -75,39 +78,65 @@ repl:
 F746ZG: compile
 	st-flash --connect-under-reset --format ihex write F746ZG_firmware.hex
 	sleep 5
-	cp flash.mpy i2c.mpy gpio_config_builder.mpy nucleo_api.mpy io_config.mpy ${FLASH}
-	cp config_io_o.hex ${FLASH}
-	cp main.py ${FLASH}
-	ls ${FLASH}
+	make F746ZG-copy
 
 F413ZH:
 	st-flash --connect-under-reset --format ihex write F413ZH_firmware.hex
 	sleep 7
-	cp flash.py i2c.py gpio_config_builder.py nucleo_api.py io_config.py ${FLASH}
-	cp config_io_o.hex ${FLASH}
-	cp main.py ${FLASH}
+	make F413ZH-copy
+
+# copies scripts to nucleo
+copy2 F746ZG-copy: compile check_volume
+	$(COPY_CMD) flash.mpy i2c.mpy gpio_config_builder.mpy nucleo_api.mpy io_config.mpy ${FLASH}
+	$(COPY_CMD) config_io_o.hex ${FLASH}
+	$(COPY_CMD) main.py ${FLASH}
+	sync
 	ls ${FLASH}
 
-#Generate Config Data
-gpio_config_data.c: gpio_config_def.py gpio_config_io.py
-	python3 ../gpio_config/gpio_config_builder.py
+copy3 F413ZH-copy: check_volume
+	$(COPY_CMD) flash.py i2c.py gpio_config_builder.py nucleo_api.py io_config.py ${FLASH}
+	$(COPY_CMD) config_io_o.hex ${FLASH}
+	$(COPY_CMD) main.py ${FLASH}
+	sync
+	ls ${FLASH}
 
-sim: gpio_config_def.py gpio_config_io.py gpio_config_data.c
-	python3 ../gpio_config/gpio_config_simulator.py
+check_volume:
+	@if [ ! -d "$(FLASH)" ]; then \
+		echo "Nucleo volume not found.  Please export FLASH=/<my_path>/PYBFLASH"; \
+		exit 1; \
+	fi
 
-check: gpio_config_def.py gpio_config_io.py gpio_config_data.c
-	python3 ../gpio_config/gpio_config_checker.py
+check_device:
+ifndef DEV
+	$(error "Nucleo device file not found")
+endif
+
+check_part:
+ifndef PART
+	$(error "PART not defined.  Please use 'make run PART=<part_id>'")
+endif
+
+check-python:
+ifeq ($(shell which python3),)
+$(error Please install python 3.6+)
+endif
+
+setup: check-python
+	python3 -m pip install rshell
+	python3 -m pip install mpy-cross
+	python3 -m pip install mpremote
 
 # ---- targets for building hex file
 
 #TOOLCHAIN_PATH=/foss/tools/riscv-gnu-toolchain-rv32i/217e7f3debe424d61374d31e33a091a630535937/bin/
-TOOLCHAIN_PATH=/opt/riscv64i/bin/
-SCRIPTS_PATH=/home/dinesha/workarea/opencore/git/mpw_bringup/mpw-2/nucleo/scripts
+#TOOLCHAIN_PATH=/opt/riscv64i/bin/
+TOOLCHAIN_PATH=/opt/riscv/bin/
+SCRIPTS_PATH=../
 #TOOLCHAIN_PATH=/opt/riscv32imc/bin/
 
 # Set the prefix for `riscvXX-unknown-elf-*`
 # On installations using `multilib`, this will be `riscv64` even for compiling to 32-bit targets
-TOOLCHAIN_PREFIX=riscv64-unknown-elf
+TOOLCHAIN_PREFIX=riscv64-unknown-linux-gnu
 #TOOLCHAIN_PREFIX=riscv32-unknown-linux-gnu
 
 #SED_CMD=sed -i '.orig' -e
@@ -133,6 +162,6 @@ hex:  ${PATTERN:=.hex}
 	#$(SED_CMD) '1,/@00/!d' $@
 
 clean:
-	rm -f *.elf *.lst *.hexe config_io_o.hex config_io_o.hex.org
+	rm -f *.elf config_io_o.hex
 
 .PHONY: clean image hex copy repl run
